"""Add user preferences and websocket sessions tables

Revision ID: 0b70656934f4
Revises: 1b8b0a15fe6c
Create Date: 2025-09-23 21:40:30.529428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b70656934f4'
down_revision: Union[str, Sequence[str], None] = '1b8b0a15fe6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='projectstatus'), nullable=False),
    sa.Column('azure_folder_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('realtime_updates', sa.Boolean(), nullable=False),
    sa.Column('auto_sync_github', sa.Boolean(), nullable=False),
    sa.Column('additional_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('websocket_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websocket_sessions_id'), 'websocket_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_websocket_sessions_session_id'), 'websocket_sessions', ['session_id'], unique=True)
    op.create_table('code_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='generationstatus'), nullable=False),
    sa.Column('generation_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.String(length=10), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_generations_generation_hash'), 'code_generations', ['generation_hash'], unique=False)
    op.create_index(op.f('ix_code_generations_id'), 'code_generations', ['id'], unique=False)
    op.create_index(op.f('ix_code_generations_project_id'), 'code_generations', ['project_id'], unique=False)
    op.create_index(op.f('ix_code_generations_status'), 'code_generations', ['status'], unique=False)
    op.create_index(op.f('ix_code_generations_user_id'), 'code_generations', ['user_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('azure_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_id'), 'project_files', ['id'], unique=False)
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.create_table('generated_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('project_file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['code_generations.id'], ),
    sa.ForeignKeyConstraint(['project_file_id'], ['project_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_files_generation_id'), 'generated_files', ['generation_id'], unique=False)
    op.create_index(op.f('ix_generated_files_id'), 'generated_files', ['id'], unique=False)
    op.create_index(op.f('ix_generated_files_project_file_id'), 'generated_files', ['project_file_id'], unique=False)
    op.drop_index(op.f('idx_file_embeddings_vector_cosine'), table_name='file_embeddings', postgresql_ops={'embedding_vector': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('github_sync_records', sa.Column('files_synced_count', sa.Integer(), nullable=False))
    op.add_column('github_sync_records', sa.Column('conflicts_resolved_count', sa.Integer(), nullable=False))
    op.add_column('github_sync_records', sa.Column('sync_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('github_sync_records', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('github_sync_records', sa.Column('branch_name', sa.String(length=255), nullable=False))
    op.add_column('github_sync_records', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_github_sync_records_project_id'), table_name='github_sync_records')
    op.drop_index(op.f('ix_github_sync_records_sync_status'), table_name='github_sync_records')
    op.drop_index(op.f('ix_github_sync_records_user_id'), table_name='github_sync_records')
    op.drop_constraint(op.f('uq_github_sync_project_repo'), 'github_sync_records', type_='unique')
    op.create_foreign_key(None, 'github_sync_records', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'github_sync_records', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_github_sync_project_repo'), 'github_sync_records', ['project_id', 'github_repository'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_github_sync_records_user_id'), 'github_sync_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_github_sync_records_sync_status'), 'github_sync_records', ['sync_status'], unique=False)
    op.create_index(op.f('ix_github_sync_records_project_id'), 'github_sync_records', ['project_id'], unique=False)
    op.drop_column('github_sync_records', 'deleted_at')
    op.drop_column('github_sync_records', 'branch_name')
    op.drop_column('github_sync_records', 'retry_count')
    op.drop_column('github_sync_records', 'sync_duration_seconds')
    op.drop_column('github_sync_records', 'conflicts_resolved_count')
    op.drop_column('github_sync_records', 'files_synced_count')
    op.create_index(op.f('idx_file_embeddings_vector_cosine'), 'file_embeddings', ['embedding_vector'], unique=False, postgresql_ops={'embedding_vector': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_generated_files_project_file_id'), table_name='generated_files')
    op.drop_index(op.f('ix_generated_files_id'), table_name='generated_files')
    op.drop_index(op.f('ix_generated_files_generation_id'), table_name='generated_files')
    op.drop_table('generated_files')
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_code_generations_user_id'), table_name='code_generations')
    op.drop_index(op.f('ix_code_generations_status'), table_name='code_generations')
    op.drop_index(op.f('ix_code_generations_project_id'), table_name='code_generations')
    op.drop_index(op.f('ix_code_generations_id'), table_name='code_generations')
    op.drop_index(op.f('ix_code_generations_generation_hash'), table_name='code_generations')
    op.drop_table('code_generations')
    op.drop_index(op.f('ix_websocket_sessions_session_id'), table_name='websocket_sessions')
    op.drop_index(op.f('ix_websocket_sessions_id'), table_name='websocket_sessions')
    op.drop_table('websocket_sessions')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
