"""Add project_chats table for chat functionality

Revision ID: 4ad086e9e217
Revises: 5daa6e0db591
Create Date: 2025-09-27 21:00:54.107655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad086e9e217'
down_revision: Union[str, Sequence[str], None] = '5daa6e0db591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('USER', 'SYSTEM', 'AI', name='messagetype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_chats_id'), 'project_chats', ['id'], unique=False)
    op.create_index(op.f('ix_project_chats_project_id'), 'project_chats', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_chats_timestamp'), 'project_chats', ['timestamp'], unique=False)
    op.create_index(op.f('ix_project_chats_user_id'), 'project_chats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_chats_user_id'), table_name='project_chats')
    op.drop_index(op.f('ix_project_chats_timestamp'), table_name='project_chats')
    op.drop_index(op.f('ix_project_chats_project_id'), table_name='project_chats')
    op.drop_index(op.f('ix_project_chats_id'), table_name='project_chats')
    op.drop_table('project_chats')
    # ### end Alembic commands ###
