"""Remove user foreign key constraints from projects and code_generations

Revision ID: d22047f97629
Revises: 751d97eea485
Create Date: 2025-09-27 19:15:47.562582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22047f97629'
down_revision: Union[str, Sequence[str], None] = '751d97eea485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('code_generations_user_id_fkey'), 'code_generations', type_='foreignkey')
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('code_generations_user_id_fkey'), 'code_generations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
