"""
Application exceptions package.
"""

from .base_exceptions import (
    BaseApplicationError,
    ValidationError,
    AuthenticationError,
    AuthorizationError,
    ResourceNotFoundError,
    ResourceConflictError,
    ServiceUnavailableError,
    RateLimitError,
    ConfigurationError,
    ExternalServiceError,
)

from .azure_entra_exceptions import (
    AzureEntraError,
    TokenExpiredError,
    InvalidTokenError,
    AuthorizationError as AzureAuthorizationError,
    TenantNotAllowedError,
    UserNotFoundError,
    UserInactiveError,
    ConsentRequiredError,
    TokenRefreshError,
    ProfileSyncError,
    AzureServiceUnavailableError,
    AzureRateLimitError,
    AzureConfigurationError,
    map_azure_entra_exception,
    is_retryable_azure_entra_error,
    get_azure_entra_error_severity,
)

from .project_exceptions import (
    ProjectError,
    ProjectNotFoundError,
    ProjectAccessDeniedError,
    ProjectCreationError,
    ProjectUpdateError,
    ProjectDeletionError,
    ProjectValidationError,
    ProjectConflictError,
    ProjectStorageError,
    ProjectFileError,
    ProjectGitHubLinkError,
    ProjectSyncError,
    ProjectQuotaExceededError,
    map_project_exception,
    is_retryable_project_error,
    get_project_error_severity,
    get_project_retry_delay,
)

from .github_exceptions import (
    GitHubError,
    GitHubAuthenticationError,
    GitHubTokenExpiredError,
    GitHubPermissionError,
    GitHubRepositoryNotFoundError,
    GitHubRateLimitError,
    GitHubSyncConflictError,
    GitHubSyncError,
    GitHubFileNotFoundError,
    GitHubCommitError,
    GitHubBranchError,
    GitHubServiceUnavailableError,
    GitHubWebhookError,
    GitHubAppError,
    GitHubAppAuthenticationError,
    GitHubAppJWTError,
    GitHubAppInstallationError,
    GitHubAppInstallationTokenError,
    GitHubAppWebhookValidationError,
    GitHubAppRateLimitError,
    map_github_exception,
    is_retryable_github_error,
    get_github_error_severity,
    get_github_retry_delay,
)

from .websocket_exceptions import (
    WebSocketError,
    WebSocketConnectionError,
    WebSocketAuthenticationError,
    WebSocketDisconnectionError,
    WebSocketMessageError,
    WebSocketBroadcastError,
    WebSocketRateLimitError,
    WebSocketSessionError,
    WebSocketHeartbeatError,
    map_websocket_exception,
    is_retryable_websocket_error,
    get_websocket_error_severity,
    get_websocket_reconnect_delay,
)

from .security_exceptions import (
    SecurityError,
    SuspiciousActivityError,
    BruteForceAttemptError,
    UnauthorizedAccessError,
    TokenManipulationError,
    DataExfiltrationAttemptError,
    InjectionAttemptError,
    SessionHijackingError,
    PrivilegeEscalationError,
    AnomalousPatternError,
    ComplianceViolationError,
    create_security_audit_log,
    determine_security_response,
    is_security_exception_retryable,
    get_security_error_context,
)

__all__ = [
    # Base exceptions
    "BaseApplicationError",
    "ValidationError",
    "AuthenticationError",
    "AuthorizationError",
    "ResourceNotFoundError",
    "ResourceConflictError",
    "ServiceUnavailableError",
    "RateLimitError",
    "ConfigurationError",
    "ExternalServiceError",
    # Azure Entra exceptions
    "AzureEntraError",
    "TokenExpiredError",
    "InvalidTokenError",
    "AzureAuthorizationError",
    "TenantNotAllowedError",
    "UserNotFoundError",
    "UserInactiveError",
    "ConsentRequiredError",
    "TokenRefreshError",
    "ProfileSyncError",
    "AzureServiceUnavailableError",
    "AzureRateLimitError",
    "AzureConfigurationError",
    "map_azure_entra_exception",
    "is_retryable_azure_entra_error",
    "get_azure_entra_error_severity",
    # Project exceptions
    "ProjectError",
    "ProjectNotFoundError",
    "ProjectAccessDeniedError",
    "ProjectCreationError",
    "ProjectUpdateError",
    "ProjectDeletionError",
    "ProjectValidationError",
    "ProjectConflictError",
    "ProjectStorageError",
    "ProjectFileError",
    "ProjectGitHubLinkError",
    "ProjectSyncError",
    "ProjectQuotaExceededError",
    "map_project_exception",
    "is_retryable_project_error",
    "get_project_error_severity",
    "get_project_retry_delay",
    # GitHub exceptions
    "GitHubError",
    "GitHubAuthenticationError",
    "GitHubTokenExpiredError",
    "GitHubPermissionError",
    "GitHubRepositoryNotFoundError",
    "GitHubRateLimitError",
    "GitHubSyncConflictError",
    "GitHubSyncError",
    "GitHubFileNotFoundError",
    "GitHubCommitError",
    "GitHubBranchError",
    "GitHubServiceUnavailableError",
    "GitHubWebhookError",
    "GitHubAppError",
    "GitHubAppAuthenticationError",
    "GitHubAppJWTError",
    "GitHubAppInstallationError",
    "GitHubAppInstallationTokenError",
    "GitHubAppWebhookValidationError",
    "GitHubAppRateLimitError",
    "map_github_exception",
    "is_retryable_github_error",
    "get_github_error_severity",
    "get_github_retry_delay",
    # WebSocket exceptions
    "WebSocketError",
    "WebSocketConnectionError",
    "WebSocketAuthenticationError",
    "WebSocketDisconnectionError",
    "WebSocketMessageError",
    "WebSocketBroadcastError",
    "WebSocketRateLimitError",
    "WebSocketSessionError",
    "WebSocketHeartbeatError",
    "map_websocket_exception",
    "is_retryable_websocket_error",
    "get_websocket_error_severity",
    "get_websocket_reconnect_delay",
    # Security exceptions
    "SecurityError",
    "SuspiciousActivityError",
    "BruteForceAttemptError",
    "UnauthorizedAccessError",
    "TokenManipulationError",
    "DataExfiltrationAttemptError",
    "InjectionAttemptError",
    "SessionHijackingError",
    "PrivilegeEscalationError",
    "AnomalousPatternError",
    "ComplianceViolationError",
    "create_security_audit_log",
    "determine_security_response",
    "is_security_exception_retryable",
    "get_security_error_context",
]
